version: "3.7"

services:
    app:
        build: .
        env_file: .env
        restart: on-failure
        command: /start-reload.sh
        volumes:
            - ./app:/app/app
        ports:
            - 8000:80

    cache:
        image: redis